<x-layouts.public :title="$job->title"> @php($lang = request()->route('lang', 'en'))     <x-hero :title="$job->title" :subtitle="$job->location . ' · ' . ucfirst($job->type ?? '')" />     <section class="container-shell mt-8 grid gap-6 lg:grid-cols-2">         <div class="space-y-4">             <div class="card-panel p-6">                 <h2 class="mb-3 text-lg font-semibold text-white">{{ $lang === 'de' ? 'Stellenbeschreibung' : 'Job Description' }}</h2>        @if(session('tracking_token'))
<div style="margin-bottom:20px; padding:20px; background:rgba(16,185,129,0.1); border:1px solid rgba(16,185,129,0.3); border-radius:12px; color:#10B981;">
    <div style="font-size:16px; font-weight:700; margin-bottom:8px;">✅ Application Submitted!</div>
    <p style="font-size:14px; margin-bottom:12px; color:#94A3B8;">Your Application ID: <strong style="color:#10B981; font-family:monospace; font-size:16px;">{{ session('tracking_token') }}</strong></p>
    <p style="font-size:13px; color:#64748B; margin-bottom:12px;">Save this ID to track your application status.</p>
    <a href="{{ route('careers.track', ['lang' => $lang, 'token' => session('tracking_token')]) }}"
       style="display:inline-flex; align-items:center; gap:6px; padding:8px 16px; border-radius:8px; background:#10B981; color:white; font-size:13px; font-weight:600; text-decoration:none;">
        Track Application →
    </a>
</div>
@endif
@if(session('status'))         <div class="text-sm text-slate-300 leading-relaxed">{!! nl2br(e($lang === 'de' && $job->description_de ? $job->description_de : $job->description)) !!}</div>             </div>             @if($job->requirements || $job->requirements_de)             <div class="card-panel p-6">                 <h2 class="mb-3 text-lg font-semibold text-white">{{ $lang === 'de' ? 'Anforderungen' : 'Requirements' }}</h2>                 <div class="text-sm text-slate-300 leading-relaxed">{!! nl2br(e($lang === 'de' && $job->requirements_de ? $job->requirements_de : $job->requirements)) !!}</div>             </div>             @endif             @if($job->benefits || $job->benefits_de)             <div class="card-panel p-6">                 <h2 class="mb-3 text-lg font-semibold text-white">{{ $lang === 'de' ? 'Vorteile' : 'Benefits' }}</h2>                 <div class="text-sm text-slate-300 leading-relaxed">{!! nl2br(e($lang === 'de' && $job->benefits_de ? $job->benefits_de : $job->benefits)) !!}</div>             </div>             @endif             <div class="card-panel p-4 flex flex-wrap gap-3 text-xs text-slate-400">                 <span>📍 {{ $job->location ?? '—' }}</span>                 <span>💼 {{ ucfirst($job->type ?? '—') }}</span>                 <span>🏢 {{ $job->department ?? '—' }}</span>                 @if($job->close_date)                     <span>📅 {{ $lang === 'de' ? 'Bewerbungsschluss' : 'Closes' }}: {{ \Carbon\Carbon::parse($job->close_date)->format('d M Y') }}</span>                 @endif             </div>         </div>         <div class="card-panel p-6">             <h2 class="mb-4 text-lg font-semibold text-white">{{ $lang === 'de' ? 'Jetzt bewerben' : 'Apply Now' }}</h2>             <x-forms.apply :job="$job" :lang="$lang" />         </div>     </section> </x-layouts.public>
